# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: noble_prize.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'noble_prize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11noble_prize.proto\x12\x05nobel\"I\n\x0f\x43\x61tegoryRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nstart_year\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_year\x18\x03 \x01(\x05\"!\n\x0eKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"5\n\x0fLaureateRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"&\n\x15LaureateCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"K\n\x17LaureateDetailsResponse\x12\x30\n\x10laureate_details\x18\x01 \x03(\x0b\x32\x16.nobel.LaureateDetails\"E\n\x0fLaureateDetails\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\nmotivation\x18\x03 \x01(\t2\xfe\x01\n\x0cNobelService\x12P\n\x18\x43ountLaureatesByCategory\x12\x16.nobel.CategoryRequest\x1a\x1c.nobel.LaureateCountResponse\x12N\n\x17\x43ountLaureatesByKeyword\x12\x15.nobel.KeywordRequest\x1a\x1c.nobel.LaureateCountResponse\x12L\n\x12GetLaureateDetails\x12\x16.nobel.LaureateRequest\x1a\x1e.nobel.LaureateDetailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'noble_prize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORYREQUEST']._serialized_start=28
  _globals['_CATEGORYREQUEST']._serialized_end=101
  _globals['_KEYWORDREQUEST']._serialized_start=103
  _globals['_KEYWORDREQUEST']._serialized_end=136
  _globals['_LAUREATEREQUEST']._serialized_start=138
  _globals['_LAUREATEREQUEST']._serialized_end=191
  _globals['_LAUREATECOUNTRESPONSE']._serialized_start=193
  _globals['_LAUREATECOUNTRESPONSE']._serialized_end=231
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_start=233
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_end=308
  _globals['_LAUREATEDETAILS']._serialized_start=310
  _globals['_LAUREATEDETAILS']._serialized_end=379
  _globals['_NOBELSERVICE']._serialized_start=382
  _globals['_NOBELSERVICE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
