# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import noble_prize_pb2 as noble__prize__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in noble_prize_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NobelServiceStub(object):
    """NobelService is the main service for querying Nobel Prize data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountLaureatesByCategory = channel.unary_unary(
                '/nobel.NobelService/CountLaureatesByCategory',
                request_serializer=noble__prize__pb2.CategoryRequest.SerializeToString,
                response_deserializer=noble__prize__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.CountLaureatesByKeyword = channel.unary_unary(
                '/nobel.NobelService/CountLaureatesByKeyword',
                request_serializer=noble__prize__pb2.KeywordRequest.SerializeToString,
                response_deserializer=noble__prize__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.GetLaureateDetails = channel.unary_unary(
                '/nobel.NobelService/GetLaureateDetails',
                request_serializer=noble__prize__pb2.LaureateRequest.SerializeToString,
                response_deserializer=noble__prize__pb2.LaureateDetailsResponse.FromString,
                _registered_method=True)


class NobelServiceServicer(object):
    """NobelService is the main service for querying Nobel Prize data.
    """

    def CountLaureatesByCategory(self, request, context):
        """1. Query: Total laureates by category between specific years
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountLaureatesByKeyword(self, request, context):
        """2. Query: Total laureates containing a specific keyword in motivation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureateDetails(self, request, context):
        """3. Query: Retrieve year, category, and motivation for a given laureate's first and last name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NobelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountLaureatesByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CountLaureatesByCategory,
                    request_deserializer=noble__prize__pb2.CategoryRequest.FromString,
                    response_serializer=noble__prize__pb2.LaureateCountResponse.SerializeToString,
            ),
            'CountLaureatesByKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.CountLaureatesByKeyword,
                    request_deserializer=noble__prize__pb2.KeywordRequest.FromString,
                    response_serializer=noble__prize__pb2.LaureateCountResponse.SerializeToString,
            ),
            'GetLaureateDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureateDetails,
                    request_deserializer=noble__prize__pb2.LaureateRequest.FromString,
                    response_serializer=noble__prize__pb2.LaureateDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nobel.NobelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nobel.NobelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NobelService(object):
    """NobelService is the main service for querying Nobel Prize data.
    """

    @staticmethod
    def CountLaureatesByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelService/CountLaureatesByCategory',
            noble__prize__pb2.CategoryRequest.SerializeToString,
            noble__prize__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountLaureatesByKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelService/CountLaureatesByKeyword',
            noble__prize__pb2.KeywordRequest.SerializeToString,
            noble__prize__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureateDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelService/GetLaureateDetails',
            noble__prize__pb2.LaureateRequest.SerializeToString,
            noble__prize__pb2.LaureateDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
